### ISSUE TITLE
Links don't make sense

### ISSUE THREAD

**Issue by abhiyandhakal** [kuosc2005/website#23]
![image](https://github.com/kuosc2005/website/assets/96732471/261bd707-751e-496e-9b98-14f55d635362)

Clicking on `Projects` here, we are sent to the page `/docs/intro`.
![image](https://github.com/kuosc2005/website/assets/96732471/0df53197-59d0-4fde-8ae5-66efcf8cebdb)

![image](https://github.com/kuosc2005/website/assets/96732471/809e82ef-cc38-4cba-937f-20c6bf30106e)
Clicking here, we are sent to the page `/docs/`.
![image](https://github.com/kuosc2005/website/assets/96732471/f25bbda5-749e-41be-a8eb-d1b22efac536)

Is this intentional? @aadarshadhakalg

**Comment by aadarshadhakalg** [comment]
No this is not intentional, we have to fix this.
