### ISSUE TITLE
Missing Contributing Guidelines, Code Contributions, Documentation Contributions, and Management Contributions Pages

### ISSUE THREAD

**Issue by aadarshadhakalg** [kuosc2005/website#6]
## Issue Description:
The KUOSC website repository is currently lacking essential documentation for various contributions and management aspects. This documentation is crucial for maintaining a transparent and efficient workflow within the community. 

The following pages are missing documentation:

- Contributing Guidelines Page: This page should provide clear instructions on how individuals can contribute to the KUOSC project, including the codebase, documentation, and other aspects of the project.
- Code Contributions Page: Detailed instructions on how to contribute code to the KUOSC project are missing. This includes steps for setting up the development environment, coding standards, submitting pull requests, and reviewing code.
- Documentation Contributions Page: The absence of documentation on how to contribute to the project's documentation hinders the growth of the project. This page should guide contributors on how to improve and expand the project's documentation resources.
- Management Contributions Page: A well-defined guide for individuals who want to contribute to the management and organization of the KUOSC project is lacking. This page should outline roles, responsibilities, decision-making processes, and how to get involved in non-technical aspects of the project.

## Reference Links:
https://community.moja.global/community/code-contribution
https://community.moja.global/community/docs-contribution
https://community.moja.global/community/management-contribution
https://community.moja.global/community/contributing

## Adding Documentation

If you want to help resolve this issue, you have to perform following steps.

1. Create fork of this repository
2. Clone the forked repository and create markdown files inside, knowledgebase folder. Each markdown file will be rendered as a page in the website. Example: https://github.com/kuosc2005/website/blob/main/knowledgebase/intro.md
3. Commit changes and create a PR referencing this issue.

Thanks.

**Comment by razzat008** [comment]
will work on this

**Comment by erwinschrodinger1** [comment]
@razzat008 Should I assign this issue to you?

**Comment by razzat008** [comment]
yes , sure 😁

**Comment by razzat008** [comment]
added in #61
