### ISSUE TITLE
bug: Vercel deploy to preview PR check fails

### ISSUE THREAD

**Issue by aadarshadhakalg** [kuosc2005/website#9]
Issue: 

Vercel deploy to preview PR check fails

Steps to reproduce:
1. Create a PR in this repo.

Additional Context:

Need to make changes to  https://github.com/kuosc2005/website/blob/main/.github/workflows/test-deploy.yml file.

**Comment by abhiyandhakal** [comment]
Looks like all other errors are fixed, except the ones about Github Pages.

**Comment by kuosc2005** [comment]
This is solved.

**Comment by erwinschrodinger1** [comment]
Looks like the issue is solved for now !
